### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by cvet** [cvet/fonline#40]
My plans in engine development:
v0.5 - Current version
v0.6 - C# as scripting language
v0.7 - Multifunctional editor
v0.8 - Singleplayer mode
v0.9 - Parallelism for server
v1.0 - First release with fixed API and further backward comparability

**Comment by cvet** [comment]
Also Documentation

**Comment by AdvancedPowerArmor** [comment]
Any estimated dates? Do you work alone?

**Comment by cvet** [comment]
> Any estimated dates? Do you work alone?

No dates. Alone.

**Comment by AdvancedPowerArmor** [comment]
Thank you sir for what you did and doing. I appreciate your hard work and knowledge.

**Comment by cvet** [comment]
Milestones described in README.md.
