### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cvet** [cvet/fonline#49]
I think thats will be md pages in Markdown here at github.

**Comment by Tab10id** [comment]
Asciidoc is better: https://asciidoctor.org/docs/what-is-asciidoc/

**Comment by Koniiko** [comment]
Pandoc's a viable solution written in Haskell -> https://pandoc.org/

**Comment by cvet** [comment]
Yeah, it can be written im github markdown but converted to html/cht/doc/etc at build phase and included to sdk output.
