### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by cvet** [cvet/fonline#62]
FOnline Engine has a long history, many fan-projects, big community, a lot of other pain... but still don't has own logo.
So I think time have been come.
If you feel power in drawing and know how Paint works then spend some time to draw great logo for great project.
For free of course ;)

Need two variants:
- Square icon (for default icon of engine binaries, favicon and other small and big targets)
- Wide logo with picture and title "FOnline Engine" (for web headings and like that)

Requirements:
- Something apocalyptic (maybe with radiation hazard but not necessary)
- Unique, not just redrawn from another logo
- Image sources for all (with layers, in big resolution and etc)
- MIT license

You feel free to discuss this thing here or directly with me (cvet@tut.by).
Thanks!

**Comment by cvet** [comment]
Logo ready!
Thanks to user Jod194!
It will be integrated in near future.
Thanks to all!

**Comment by kaldaFO** [comment]
cvet hello! can u join discord we wanna pay you for your job with new FO engine. maybe we make fonline great again together! https://discord.gg/Darstqa   😜😜👍👍
