### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by cvet** [cvet/fonline#63]
If you want to contribute to development, there are several ways how you can help out.
Check this document:
https://github.com/cvet/fonline/blob/master/CONTRIBUTING.md
Any help is appreciated.

**Comment by Tab10id** [comment]
Is fonline ready for pull requests or there need some more time for engine stabilization?

**Comment by cvet** [comment]
> Is fonline ready for pull requests or there need some more time for engine stabilization?

From architecturally point of view engine won't change but there a lot of issues that must be complete before release.
All what need to do before release described in Todo list generated from source code and first part of Roadmap.
Also need document all public API (script API, cmake contribution, etc), write some tutorial.
After this API will be finally fixed and first release version shipped.
So current contributions mostly about speeding up of first release.

**Comment by cvet** [comment]
> Is fonline ready for pull requests or there need some more time for engine stabilization?

Yeah, I think you are right - firstly I will make first release version and then return to this question.
