### ISSUE TITLE
Critter::GetItemsSlot - ошибка в названии?

### ISSUE THREAD

**Issue by FakelsHub** [cvet/fonline#64]
Метод называется `void Critter::GetItemsSlot` но в коде метода используется push_back, и нет возвращаемого значения, тогда метод должен называться Set
https://github.com/cvet/fonline/blob/83c10c315ea6f2c5ce6a83a608f287d9c619fa9d/Source/Server/Critter.cpp#L346

**Comment by FakelsHub** [comment]
О черт, я понял, нет ошибки, возврат через добавление в вектор предмета или всех предметов в инвентаре.

**Comment by cvet** [comment]
Лучше смотреть пока на уровень выше, апи из ScriptApi_...h файлов, которые попадают в папблик, а низкий уровенье еще успеет подятянуться.
